sider/runners

- images/goodcheck/Dockerfile
I forgot to include `images/goodcheck/Dockerfile` :pray:
> Fix goodcheck image - Dockerfile is forgotten

- lib/node_harness/runners/phinder/processor.rb
- test/smokes/phinder/expectations.rb
- test/smokes/phinder/rule_option_as_config_file/index.php
- test/smokes/phinder/rule_option_as_config_file/my_phinder.yml
- test/smokes/phinder/rule_option_as_config_file/phinder.yml
- test/smokes/phinder/rule_option_as_config_file/sider.yml
The error message: "Checking if required file exists: phinder.yml"
> Fix error when setting a config file path to `rule` option

- .circleci/config.yml
https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
According to this article, we have to specify "tag filters" to make CircleCI run when a Git tag is pushed.
> Make CircleCI run when a Git tag is pushed

- Gemfile
- Gemfile.lock
> Add `rake` gem to top-level

- .rubocop.yml
- lib/node_harness/cli.rb
- lib/node_harness/runners/rubocop/processor.rb
- test/cli_test.rb
- test/result_test.rb
Also, I renamed the module `Rubocop` with `RuboCop.`
> Enable skipped tests

- Rakefile
- lib/node_harness/testing/smoke.rb
- sig/node_harness.rbi
- sig/node_harness/testing.rbi
- sig/polyfill.rbi
- sig/polyfills/kernel.rbi
- sig/polyfills/unification_assertion.rbi
> Fix type errors of testing module

- lib/node_harness/location.rb
- sig/node_harness.rbi
- sig/node_harness/location.rbi
- Better type-checking
- Some refactorings
> Improve Location class

- Rakefile
Usage:
$ rake release'[0.1.0]' DRYRUN=1
> Add dry-run mode to release task

- lib/node_harness/nodejs.rb
- sig/node_harness.rbi
> Show Node.js runtime versions

- Gemfile
- Gemfile.lock
- Rakefile
https://github.com/ybiquitous/aufgaben
> Replace release task with gem

- .circleci/config.yml
> Bump Ruby from 2.5.3 to 2.6.4 on CircleCI

- images/Dockerfile.ruby.erb
- images/brakeman/Dockerfile
- images/brakeman/Dockerfile.erb
- images/brakeman/Gemfile
- images/goodcheck/Dockerfile
- images/goodcheck/Dockerfile.erb
- images/goodcheck/Gemfile
- images/haml_lint/Dockerfile
- images/haml_lint/Dockerfile.erb
- images/haml_lint/Gemfile
- images/querly/Dockerfile
- images/querly/Dockerfile.erb
- images/querly/Gemfile
- images/rails_best_practices/Dockerfile
- images/rails_best_practices/Dockerfile.erb
- images/rails_best_practices/Gemfile
- images/reek/Dockerfile
- images/reek/Dockerfile.erb
- images/reek/Gemfile
- images/rubocop/Dockerfile
- images/rubocop/Dockerfile.erb
- images/rubocop/Gemfile
- images/scss_lint/Dockerfile
- images/scss_lint/Dockerfile.erb
- images/scss_lint/Gemfile
This uses `bundle install --system` via `Gemfile` instead of `gem install`.
By this, Dependabot auto pull request will help us.
Related to #99
> Install default gems via `Gemfile`

- images/Dockerfile.python.erb
- images/flake8/Dockerfile
- images/flake8/Dockerfile.erb
- images/flake8/Pipfile
Like #99, I want to install Flake8 via Pipenv.
> Use Pipenv to address the dependency of Flake8

- .github/workflows/release.yml
Via https://github.com/marketplace/actions/gh-release
> Auto generate release on tags pushed via Actions

- images/cppcheck/Dockerfile
- images/cppcheck/Dockerfile.erb
> Optimize Cppcheck Docker image via multi-stage

- Gemfile
- Gemfile.lock
See <https://github.com/ybiquitous/aufgaben/blob/master/CHANGELOG.md>
> Bump aufgaben to 0.1.0 (using tag)

- images/Dockerfile.npm.erb
- images/coffeelint/Dockerfile
- images/eslint/Dockerfile
- images/jshint/Dockerfile
- images/stylelint/Dockerfile
- images/stylelint/Dockerfile.erb
- images/tslint/Dockerfile
- images/tyscan/Dockerfile
`npm config set` command saves `${RUNNER_USER_HOME}/.npmrc` file.
- https://docs.npmjs.com/cli/config
- https://docs.npmjs.com/misc/config
> Add `.npmrc` for common settings

- lib/runners/processor.rb
- lib/runners/processor/brakeman.rb
- lib/runners/processor/checkstyle.rb
- lib/runners/processor/code_sniffer.rb
- lib/runners/processor/coffeelint.rb
- lib/runners/processor/cppcheck.rb
- lib/runners/processor/eslint.rb
- lib/runners/processor/flake8.rb
- lib/runners/processor/go_vet.rb
- lib/runners/processor/golint.rb
- lib/runners/processor/gometalinter.rb
- lib/runners/processor/goodcheck.rb
- lib/runners/processor/haml_lint.rb
- lib/runners/processor/javasee.rb
- lib/runners/processor/jshint.rb
- lib/runners/processor/ktlint.rb
- lib/runners/processor/misspell.rb
- lib/runners/processor/phinder.rb
- lib/runners/processor/phpmd.rb
- lib/runners/processor/pmd_java.rb
- lib/runners/processor/querly.rb
- lib/runners/processor/rails_best_practices.rb
- lib/runners/processor/reek.rb
- lib/runners/processor/rubocop.rb
- lib/runners/processor/scss_lint.rb
- lib/runners/processor/stylelint.rb
- lib/runners/processor/swiftlint.rb
- lib/runners/processor/tslint.rb
- lib/runners/processor/tyscan.rb
- sig/runners.rbi
For details, please see each commit.
> [Refactor] Processor class and sub classes

- images/checkstyle/Dockerfile
- images/checkstyle/Dockerfile.erb
- images/checkstyle/pom.xml
- lib/runners/processor/checkstyle.rb
> Manage Checkstyle dependency via Maven

- images/Dockerfile.java.erb
- images/checkstyle/Dockerfile
- images/checkstyle/Dockerfile.erb
- images/checkstyle/checkstyle
- lib/runners/processor/checkstyle.rb
- Add a common Docker file for Java (installing dependencies via Maven)
- Add a wrapper shell script to running Checkstyle
- Remove unused code about a `locale` setting
- See https://help.sider.review/tools/java/checkstyle#configuration
> [Refactor] Checkstyle runner

- images/ktlint/Dockerfile
- images/ktlint/Dockerfile.erb
- images/ktlint/ktlint
- images/ktlint/pom.xml
> Install ktlint via Maven

- images/pmd_java/Dockerfile
- images/pmd_java/Dockerfile.erb
- images/pmd_java/pmd
- images/pmd_java/pom.xml
- lib/runners/processor/pmd_java.rb
- test/smokes/pmd_java/expectations.rb
> Install PMD Java via Maven

- lib/runners/processor/pmd_java.rb
- test/smokes/pmd_java/expectations.rb
- test/smokes/pmd_java/success/src/Hello.java
> Add "security" to the default rulesets of PMD Java

- lib/runners/processor/checkstyle.rb
- lib/runners/processor/javasee.rb
- lib/runners/processor/pmd_java.rb
> Show Java runtime versions for Java based tools

- lib/runners.rb
- lib/runners/cli.rb
- lib/runners/workspace.rb
- sig/polyfill.rbi
- sig/runners.rbi
- test/workspace_test.rb
> Receive an SSH key with an environment variable

- lib/runners/processor/rubocop.rb
- test/smokes/rubocop/expectations.rb
- test/smokes/rubocop/gem_install/expectations.rb
> Add deprecation warning for too old RuboCop versions

- goodcheck.yml
Using https://github.com/sider/goodcheck-rules
> Enable Goodcheck

- lib/runners/issues.rb
- lib/runners/results.rb
- sig/runners.rbi
- test/harness_test.rb
- test/issue_test.rb
- test/result_test.rb
- Remove unused `Issues::Identified` class
- Remove unused `Result::Success::InvalidIssue` class
> [Refactor] Issues and Result class

- lib/runners/shell.rb
- sig/runners.rbi
- test/processor_test.rb
- test/shell_test.rb
New options:
- `:trace_stdout`
- `:trace_stderr`
- `:raise_on_failure`
- `:is_success`
> Add options to `Shell#capture3_trace`

- images/Dockerfile.base.erb
- images/Dockerfile.end.erb
- images/brakeman/Dockerfile
- images/checkstyle/Dockerfile
- images/code_sniffer/Dockerfile
- images/coffeelint/Dockerfile
- images/cppcheck/Dockerfile
- images/eslint/Dockerfile
- images/flake8/Dockerfile
- images/go_vet/Dockerfile
- images/golint/Dockerfile
- images/gometalinter/Dockerfile
- images/goodcheck/Dockerfile
- images/haml_lint/Dockerfile
- images/javasee/Dockerfile
- images/jshint/Dockerfile
- images/ktlint/Dockerfile
- images/misspell/Dockerfile
- images/phinder/Dockerfile
- images/phpmd/Dockerfile
- images/pmd_java/Dockerfile
- images/querly/Dockerfile
- images/rails_best_practices/Dockerfile
- images/reek/Dockerfile
- images/rubocop/Dockerfile
- images/scss_lint/Dockerfile
- images/stylelint/Dockerfile
- images/swiftlint/Dockerfile
- images/tslint/Dockerfile
- images/tyscan/Dockerfile
Why?
----
I think that frequently changed files (= Runners source code) should be last in Dockerfile.
If they would be first, Docker build cache would be cleared every on code changed.
Thus, development time would increase much.
> Move Runners code copy to last

- Gemfile
- Gemfile.lock
- bin/runners
> Add Bugsnag to notify any errors

- lib/runners/issues.rb
- lib/runners/location.rb
- sig/polyfill.rbi
- sig/runners/location.rbi
- test/issue_test.rb
- test/location_test.rb
- test/result_test.rb
I think that StrongJSON's declarative way is more clear, readable and less code than the `#valid?` method's logic.
> [Refactor] `Location` validation via StrongJSON

- images/swiftlint/Dockerfile
- images/swiftlint/Dockerfile.erb
- images/swiftlint/fix-CryptoSwift-not-found.patch
Create and apply a patch to lock [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift.git).
Fix #315
> Fix SwiftLint build failure

- lib/runners/processor/goodcheck.rb
- test/smokes/goodcheck/expectations.rb
- test/smokes/goodcheck/invalid_config_file/goodcheck.yml
- Prevent `JSON::ParserError` as possible.
- Fail fast when `goodcheck test` command fails.
> Improve Goodcheck error message

- lib/runners/processor/checkstyle.rb
For example:
> REXML::ParseException · Start tag isn't ended Line: 436 Position: 90112 Last 80 unconsumed characters
But sadly I cannot verify with a smoke test...
> Improve Checkstyle invalid XML error message

- README.md
> Add ShellCheck to README

- .github/workflows/release.yml
See https://github.com/sider/devon_rex/pull/83
> Fix GitHub releasing via Actions

- lib/runners/ruby/lockfile_loader.rb
- lib/runners/ruby/lockfile_loader/lockfile.rb
- sig/runners/ruby.rbi
Split a big method `#ensure_lockfile` to some helper methods.
> [Refactor] `Ruby::LockfileLoader`

- .github/workflows/bump_analyzers.yml
- Rakefile
- lib/tasks/bump_analyzers.rb
- Add a new Rake task `bump_analyzers`.
- Run the task on schedule.
- https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#default-environment-variables
- https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
Fixes #130
> Create pull requests to bump an analyzer via GitHub Actions

- .github/workflows/bump_analyzers.yml
This action works on schedule with #362 and #363.
Daily is too often.
> Change bump_analyzers interval from daily to monthly

- .github/workflows/bump_analyzers.yml
- Rakefile
- lib/tasks/bump/analyzers.rb
- lib/tasks/bump/devon_rex.rb
- Rename Rake task: `bump_analyzers` -> `bump:analyzers`
- Rename Rake task: `dockerfile:bump_devon_rex` -> `bump:devon_rex`
> Refactor Rake tasks about `bump:*`

- CHANGELOG.md
- bin/runners
https://github.com/sider/runners/blob/f64b2b4d822f217eec4cb251252ab2c570c0aeea/bin/runners#L24
> Copy `ARGV` for notifying to Bugsnag correctly

- lib/runners/processor/eslint.rb
> [ESLint] Improve a log message when no rule ID found

- README.md
- lib/runners/testing/smoke.rb
- sig/polyfills/kernel.rbi
- sig/runners/testing.rbi
- Improve the logic using the `ONLY` environment variable.
- Add description about smoke testing to README.
> Improve smoke testing

- CHANGELOG.md
- lib/runners/processor.rb
- test/processor_test.rb
- test/smokes/eslint/expectations.rb
- test/smokes/rubocop/expectations.rb
- test/smokes/rubocop/gem_install/expectations.rb
> Improve deprecation message for older versions

- CHANGELOG.md
- lib/runners/harness.rb
- sig/polyfill.rbi
- sig/runners.rbi
- test/harness_test.rb
In order to show what is wrong on the log UI.
> Output an unexpected error message to the trace log

- CHANGELOG.md
- lib/runners/processor/eslint.rb
> [ESLint] Fix type error when no location info

- CHANGELOG.md
- images/swiftlint/Dockerfile
- images/swiftlint/Dockerfile.erb
- lib/runners/processor/swiftlint.rb
- test/smokes/swiftlint/expectations.rb
For details, see belows:
- Release: https://github.com/realm/SwiftLint/releases/tag/0.37.0
- Compare: https://github.com/realm/SwiftLint/compare/0.36.0...0.37.0
> Bump SwiftLint from 0.36.0 to 0.37.0

- CHANGELOG.md
- lib/runners/processor/rubocop.rb
- test/smokes/rubocop/expectations.rb
- test/smokes/rubocop/gem_install/expectations.rb
- test/smokes/rubocop/rails_and_performance/.rubocop.yml
- test/smokes/rubocop/rails_and_performance/app/foo.rb
- test/smokes/rubocop/rails_and_performance/sider.yml
- test/smokes/rubocop/rails_and_performance_old/.rubocop.yml
- test/smokes/rubocop/rails_and_performance_old/Gemfile
- test/smokes/rubocop/rails_and_performance_old/app/foo.rb
- test/smokes/rubocop/rails_and_performance_old/sider.yml
- Strip a verbose cop name from an issue message.
- Add a link to a cop document on GitHub.
- Simplify an unexpected error message.
> [RuboCop] Empower runner

- CHANGELOG.md
- lib/runners/processor/swiftlint.rb
- test/smokes/swiftlint/expectations.rb
> [SwiftLint] Show a warning when no linting files

- CHANGELOG.md
- lib/runners/processor/cppcheck.rb
- test/smokes/cppcheck/expectations.rb
- test/smokes/cppcheck/unexpected_error/sider.yml
> [Cppcheck] Show warning and succeed when no linting files

- images/rubocop/Dockerfile
- images/rubocop/Dockerfile.erb
- images/rubocop/default_rubocop.yml
- lib/runners/processor/rubocop.rb
The heredoc code in `rubocop.rb` -> the actual file in the Docker container.
> [Refactor] Move the default RuboCop config file

- goodcheck.yml
- lib/runners.rb
- lib/runners/errors.rb
- lib/runners/harness.rb
- lib/runners/nodejs.rb
- lib/runners/processor.rb
- lib/runners/ruby.rb
- lib/runners/ruby/gem_installer/spec.rb
- lib/runners/shell.rb
- lib/runners/workspace.rb
- sig/runners.rbi
> Introduce error class hierarchy

- .github/workflows/bump_analyzers.yml
- lib/tasks/bump/analyzers.rb
Also, this changes the cron schedule on GitHub Actions to verify the task's behavior.
> Add cpplint to `rake bump:analyzers`

- CHANGELOG.md
- lib/runners/processor/pmd_java.rb
- test/smokes/pmd_java/expectations.rb
- `rule`
- `ruleset`
- `priority`
See also <https://github.com/pmd/pmd.github.io/blob/093660585d5b8c4f249aaf3337321eec1ba6289f/report_2_0_0.xsd#L28-L45>
> [PMD Java] Save issue details

- CHANGELOG.md
- lib/runners/processor/reek.rb
- test/smokes/reek/expectations.rb
- More simple (trimming a rule ID).
- Wrap `context` with back-quotes (it is almost a class or method identifier).
> [Reek] Improve issue message

- CHANGELOG.md
- lib/runners/processor/haml_lint.rb
- test/smokes/haml_lint/expectations.rb
See <https://github.com/sds/haml-lint/tree/master/lib/haml_lint/linter#readme>
> [HAML-Lint] Save issue link and severity

- lib/runners/processor/eslint.rb
- querly.yml
See <https://github.com/sider/runners/pull/577#discussion_r356373186>
> [Refactor] Avoid `Dir.tmpdir` as possible

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/runners.rb
- lib/runners/changes.rb
- lib/runners/harness.rb
- lib/runners/results.rb
- lib/runners/workspace.rb
- lib/runners/workspace/git.rb
- sig/polyfills/git_diff_parser.rbi
- sig/runners.rbi
- sig/runners/workspace.rbi
- test/changes_test.rb
- test/result_test.rb
- test/workspace/git_test.rb
Resolve #574
Using `Workspace::Git`, we can detect the issues shows up in the change or not.
So, I updated the filtering process with `GitDiffParser`.
> Filter issues with the "diff lines"

- lib/runners/processor.rb
- lib/runners/processor/eslint.rb
- lib/runners/processor/rubocop.rb
- sig/polyfill.rbi
- sig/runners.rbi
- test/processor_test.rb
- test/smokes/eslint/expectations.rb
- test/smokes/rubocop/expectations.rb
See https://github.com/sider/sider-docs/pull/276
> Show deadline on deprecation warning

- Rakefile
For debugging in local machine.
> Add `docker:shell` rake task

- README.md
I wrote a "Developer guide" for this project on README.
Please give me any feedback!
> Add developer guide

- .rubocop.yml
- CHANGELOG.md
- lib/runners/cli.rb
- lib/runners/processor.rb
- lib/runners/schema/trace.rb
- lib/runners/trace_writer.rb
- sig/polyfill.rbi
- sig/runners.rbi
- test/harness_test.rb
- test/nodejs_test.rb
- test/processor_test.rb
- test/ruby_test.rb
- test/shell_test.rb
- test/trace_writer_test.rb
What?
-----
- Added `file` field to `ci_config` entry.
- Added `duration_in_ms` field to `message` entry.
- Added `truncated` field to some types' entry.
- Output total elapsed time.
Why?
----
- To improve the log page on Sider UI.
> Renewal trace

- .prettierignore
- .prettierrc.yaml
- Gemfile
- Gemfile.lock
- lefthook.yml
See https://github.com/sider/runners/pull/632#issuecomment-569180123
> Add leftfook and run prettier on pre-commit

- lib/runners/harness.rb
- lib/runners/results.rb
- sig/runners.rbi
- test/result_test.rb
See https://github.com/sider/runners/pull/655#discussion_r364537300
> Refactor Results::Success#filter_issues to mutate its attribute

- CHANGELOG.md
- lib/runners/processor/rubocop.rb
- test/smokes/rubocop/rails_and_performance/Gemfile
- test/smokes/rubocop/rails_and_performance/Gemfile.lock
- test/smokes/rubocop/rails_and_performance/sider.yml
> Add more plugins to OPTIONAL_GEMS

- CONTRIBUTING.md
- README.md
- docs/how-to-write-a-new-runner.md
> Add contributing guide

- CHANGELOG.md
- lib/runners/processor/haml_lint.rb
- lib/runners/processor/rubocop.rb
- test/smokes/haml_lint/expectations.rb
- test/smokes/haml_lint/optional_gems_are_installed_via_gemfile/.rubocop.yml
- test/smokes/haml_lint/optional_gems_are_installed_via_gemfile/Gemfile
- test/smokes/haml_lint/optional_gems_are_installed_via_gemfile/test.haml
Similar to #683
Also, I added [rubocop-sequel](https://github.com/rubocop-hq/rubocop-sequel)
to haml_lint.rb as well as rubocop.rb.
> Add more plugins to OPTIONAL_GEMS in haml_lint.rb

- README.md
> Improve a bit wording on readme

- CHANGELOG.md
- lib/runners/processor/rubocop.rb
- https://rubygems.org/gems/gitlab-styles
- https://gitlab.com/gitlab-org/gitlab-styles
> [RuboCop] Add `gitlab-styles` to optional gem list

- CHANGELOG.md
- lib/runners/cli.rb
- lib/runners/workspace.rb
This aims to make it easier to know the running version from traces.
> Show Runners version and GUID to trace

- README.md
- docs/how-to-write-a-new-runner.md
> [Docs] How to write a new runner

- CHANGELOG.md
- lib/runners/changes.rb
- lib/runners/processor.rb
- sig/polyfill.rbi
- sig/runners.rbi
The current log page is noisy:
> Aggregate log entries by `delete_unchanged_files` method

- CHANGELOG.md
- lib/runners/processor.rb
- lib/runners/processor/go_vet.rb
- lib/runners/processor/golint.rb
- lib/runners/processor/gometalinter.rb
- sig/runners.rbi
- test/smokes/go_vet/expectations.rb
- test/smokes/golint/expectations.rb
- test/smokes/gometalinter/expectations.rb
> Add deprecation warning to golint, govet and gometalinter

- README.md
Add descriptions about EditorConfig and Lefthook.
> Update "Developer guide" on README

- lib/runners/harness.rb
- lib/runners/processor.rb
- sig/polyfill.rbi
- sig/runners.rbi
- test/processor_test.rb
- test/ruby_test.rb
For safety and maintenancibility.
> [Refactor] More strict type-check

- lib/tasks/bump/analyzers.rb
Some analyzers have been added newly.
> Update list for `rake bump:analyzers`

- README.md
- lib/tasks/readme/generate.rb
- Change format: list to table
- Fix doc links
> Fix analyzers list on README

- CHANGELOG.md
- lib/runners/config.rb
- lib/runners/harness.rb
- test/config_test.rb
- test/harness_test.rb
- test/smokes/checkstyle/expectations.rb
- test/smokes/code_sniffer/expectations.rb
- test/smokes/detekt/expectations.rb
- test/smokes/eslint/expectations.rb
- test/smokes/flake8/expectations.rb
- test/smokes/goodcheck/expectations.rb
- test/smokes/haml_lint/expectations.rb
- test/smokes/javasee/expectations.rb
- test/smokes/jshint/expectations.rb
- test/smokes/ktlint/expectations.rb
- test/smokes/misspell/expectations.rb
- test/smokes/phinder/expectations.rb
- test/smokes/phpmd/expectations.rb
- test/smokes/pmd_java/expectations.rb
- test/smokes/rails_best_practices/expectations.rb
- test/smokes/rubocop/expectations.rb
- test/smokes/scss_lint/expectations.rb
- test/smokes/stylelint/expectations.rb
- test/smokes/swiftlint/expectations.rb
- test/smokes/tslint/expectations.rb
- Output an error message to the trace.
- Improve error messages.
> More kindful error message on invalid configuration

- .circleci/config.yml
> Fix Docker image tagging on CircleCI

- .github/workflows/build.yml
https://github.com/sider/devon_rex/blob/b39bfecb61eaa15b69a6cee0bfb226c53dedc9ad/.github/workflows/build.yml#L11-L25
> Fix "[skip ci]" on Actions

- lib/runners/shell.rb
- test/shell_test.rb
I will use this new option on PR #813.
> Add `chdir` option to `Shell#capture3_trace` method

- .github/workflows/build.yml
I want to fix the error.
https://github.com/sider/runners/runs/499924076?check_suite_focus=true
> Fix check_skip to support multiple lines of commit messages

- lib/runners/nodejs.rb
- sig/runners/nodejs.rbi
- test/nodejs_test.rb
I will use this new method in PR #813.
> Extract `Nodejs#list_installed_nodejs_deps` method

- lib/runners/cli.rb
- lib/runners/harness.rb
- sig/runners.rbi
- test/harness_test.rb
This change is just a refactoring.
> Remove the name `ci_config` as possible

- lib/runners/harness.rb
- lib/runners/processor.rb
- sig/polyfill.rbi
- sig/polyfills/kernel.rbi
- sig/runners.rbi
This change is a simple refactoring.
> Refactor `Processor` and `Harness` classes

- CHANGELOG.md
- lib/runners/processor/reek.rb
- test/smokes/reek/expectations.rb
- test/smokes/reek/option_config/a.rb
- test/smokes/reek/option_config/my-reek.yml
- test/smokes/reek/option_config/sider.yml
- test/smokes/reek/option_target/lib/a.rb
- test/smokes/reek/option_target/lib/sub/b.rb
- test/smokes/reek/option_target/not_target.rb
- test/smokes/reek/option_target/sider.yml
- test/smokes/reek/option_target/test/not_target_test.rb
- test/smokes/reek/option_target/test/target_test.rb
This change introduces the new following options for `sider.yml`:
- `target` - files or directories to analyze
- `config` - `--config` option of Reek
Fix #822
Doc update: https://github.com/sider/sider-docs/pull/325
> [Reek] Support new options

- .github/workflows/build.yml
To see the execution time for each test.
> Set `--verbose` to `rake test` on CI

- CHANGELOG.md
- lib/runners/processor/pmd_java.rb
- test/smokes/pmd_java/expectations.rb
- Make the issue ID human-readable (no hash string).
- Remove duplicated `object.rule` property.
Fix #747
> [PMD Java] Improve issues result

- lib/runners/processor/rubocop.rb
> [RuboCop] Improve trace message a bit

- Gemfile
This aims not to install extra gems and to reduce the memory usage on production.
https://github.com/sider/runners/blob/bc6e793166ebd62128990759ab3dc9348591c8ea/lib/runners/testing/smoke.rb#L1-L4
> Move gems for smoke test in Gemfile

- Gemfile
- Gemfile.lock
- lib/runners/testing/smoke.rb
- sig/runners/testing.rbi
Using the [rainbow](https://github.com/sickill/rainbow) gem.
> [Test] Colored trace output of smoke test

- .github/workflows/notify_build_to_bugsnag.yml
See https://docs.bugsnag.com/build-integrations/
> [Actions] Add notify script for Bugsnag

- CHANGELOG.md
- lib/runners/ignoring.rb
- lib/runners/shell.rb
- test/processor_test.rb
- test/shell_test.rb
> Fix Ignoring to support many files in the `ignore` configuration

- CHANGELOG.md
- lib/runners/processor/remark_lint.rb
> [remark-lint] More relax constraints

- .github/workflows/notify_build_to_bugsnag.sh
- .github/workflows/notify_build_to_bugsnag.yml
See <https://github.com/sider/runners/actions/runs/71834099>
> Fix Bugsnag upload script

- lib/runners/changes.rb
- lib/runners/processor/detekt.rb
- lib/runners/processor/javasee.rb
- lib/runners/processor/ktlint.rb
- lib/runners/processor/pmd_java.rb
- lib/runners/processor/stylelint.rb
- test/changes_test.rb
- https://ruby-doc.org/core-2.7.1/File.html#method-c-fnmatch-3F
- https://ruby-doc.org/core-2.7.1/File/Constants.html
> [Refactor] Use `File::FNM_EXTGLOB` for `Changes#deletable?`

- lib/runners/testing/smoke.rb
- sig/runners/testing.rbi
I made these changes for the class:
* Remove `#with_data_container` and make the class use Bind mounts
* Remove `Configuration` and `configs`
Close #983
> Refactor Testing::Smoke

- test/smokes/fxcop/expectations.rb
To reduce diffs on other PRs, see #922 for example.
> Apply Prettier for FxCop smoke test code

- images/swiftlint/Dockerfile
- images/swiftlint/Dockerfile.erb
- Do not use the `root` user.
- Use `curl` instead of `git clone` to download the source code.
> [SwiftLint] Improve Docker image

- CHANGELOG.md
- lib/runners/processor/swiftlint.rb
- test/smokes/swiftlint/expectations.rb
- Save a severity for an issue object.
- Add a link about a detected issue.
- Simplify the error handling.
- Refactoring.
> [SwiftLint] Some improvements

- images/javasee/Dockerfile
- images/javasee/Dockerfile.erb
- No `USER root`.
- Remove unused files.
> Refactor JavaSee Dockerfile

- images/golangci_lint/Dockerfile
- images/golangci_lint/Dockerfile.erb
Copy the binary from the published official Docker image.
See https://hub.docker.com/r/golangci/golangci-lint
> Refactor GolangCI-Lint Dockerfile

- images/hadolint/Dockerfile
- images/hadolint/Dockerfile.erb
Copy the binary from the published official Docker image.
See https://hub.docker.com/r/hadolint/hadolint
> Refactor hadolint Dockerfile

- lib/runners/processor/detekt.rb
This reduce the process code a bit.
> [detekt] Some refactorings

- lib/tasks/bump/analyzers.rb
Support also the format: `COPY --from=name:version`
[skip ci]
> Fix `bump:analyzers` rake task

- images/hadolint/Dockerfile
- images/hadolint/Dockerfile.erb
> [hadolint] Use build layer in Dockerfile

- images/shellcheck/Dockerfile
- images/shellcheck/Dockerfile.erb
> [ShellCheck] Use build layer in Dockerfile

- lib/runners/processor/misspell.rb
Simplify the processor class a bit.
> [Misspell] Refactoring

- .github/workflows/build.yml
See https://gist.github.com/ybiquitous/c80f15c18319c63cae8447a3be341267
> Fix "[skip ci]" on GH Actions

- .github/workflows/build.yml
See https://github.com/sider/devon_rex/pull/204
> Fix `check_skip` on GH Actions

- CHANGELOG.md
- lib/runners/cli.rb
This change aims to make our debugging easier.
> Log issues count

- lib/runners/testing/smoke.rb
- sig/runners/testing.rbi
- Make the test output readable.
- Check duplicate test. Fix #1081
- Refactoring to improve the readability.
- Remove the unused method.
> Improve smoke test

- README.md
- Rakefile
- Set `--workdir` option.
- Add the description to README.
> Improve `rake docker:shell`

- test/smokes/cppcheck/expectations.rb
> Change Cppcheck version on smoke test to pass build fail

- .dependabot/config.yml
> Dependabot ignore `strong_json`

- CHANGELOG.md
- lib/runners/workspace/git.rb
- test/workspace/git_test.rb
> Add `git-blame` failed exception

- CHANGELOG.md
- lib/runners/harness.rb
- lib/runners/ignoring.rb
- test/ignoring_test.rb
To look into the issue #1142 and #1144.
> Output trace more

- CHANGELOG.md
- lib/runners/ignoring.rb
- sig/polyfill.rbi
- sig/runners/ignoring.rbi
- sig_new/pathname.rbs
- sig_new/runners/ignoring.rbs
- sig_new/tempfile.rbs
- test/ignoring_test.rb
[git-check-ignore](https://git-scm.com/docs/git-check-ignore) does not work but I cannot find the cause. 🤷 
So, I will try [git-ls-files](https://git-scm.com/docs/git-ls-files) instead to fix the bug.
Fix #1144
> Use git-ls-files instead of git-check-ignore

- lib/runners/ignoring.rb
> Output deleted ignored file count to trace

- CHANGELOG.md
- lib/runners/processor/pylint.rb
- test/smokes/pylint/expectations.rb
- test/smokes/pylint/no_file/sider.yml
If there is no file in the folder, the error occurs in Pylint.
> Fix no file error in Pylint

- README.md
- analyzers.yml
This PR fixes the URLs to the [help.sider.review](https://help.sider.review):
- PHP_CodeSniffer
- Rails Best Practices
Related to https://github.com/sider/sider-docs/pull/435
- ~~Add a new [changelog](https://github.com/sider/runners/blob/master/CHANGELOG.md) entry if this change is notable.~~
=> This change is not notable.
> Fix doc path on readme [skip ci]

- test/smokes/code_sniffer/expectations.rb
- test/smokes/eslint/prefer_npm_install_true_to_eslintrc/package.json
- test/smokes/rails_best_practices/expectations.rb
This PR tries fixing the failed smoke tests on the `master` branch.
Some doc-URL related failures are due to PR #1165.
- Add a new [changelog](https://github.com/sider/runners/blob/master/CHANGELOG.md) entry if this change is notable. → Not notable.
> Fix failed smoke tests

- lib/runners/testing/smoke.rb
To make debugging easier.
None.
> Show `JOBS` in running smoke test

- .github/workflows/build.yml
SwiftLint smoke test sometimes has failed due to unknown reasons.
This change aims to retry it automatically.
None.
→ This is not notable.
> [SwiftLint] Retry unstable smoke test

- lib/runners/analyzers.rb
- sig/polyfill.rbi
Use the built-in library simply.
None.
→ Not notable.
> Use `File.expand_path()` instead of `Pathname(__dir__).join()`

- .github/dependabot.yml
- CHANGELOG.md
- images/rails_best_practices/Gemfile
- lib/runners/processor/rails_best_practices.rb
- test/smokes/rails_best_practices/expectations.rb
I've patched the bug of Rails Best Practices. But the patched version is not released yet.
Related to #1216
> [Rails Best Practices] Fix invalid line number

- CHANGELOG.md
- images/rails_best_practices/Gemfile
- lib/runners/processor/rails_best_practices.rb
- test/smokes/rails_best_practices/expectations.rb
- test/smokes/rails_best_practices/invalid_line_number/app/views/articles/show.html.erb
This is a re-challenge of PR #1232.
https://github.com/flyerhzm/code_analyzer/compare/331749f94f4ff0f6b1b4cd976363057540fd826a...e31ce438d3858df055bf85334003f29e1bd1673d
Related to #1232
> [Rails Best Practices] Re-challenge to fix invalid line number

- CHANGELOG.md
- Rakefile
To speed up `docker build`. devon_rex has already used it.
See also:
- https://docs.docker.com/develop/develop-images/build_enhancements/
- https://github.com/sider/devon_rex/pull/226
None.
> Use Docker BuildKit

- .github/stale.yml
Stale Bot can reduce our management costs for issues.
See https://probot.github.io/apps/stale/
None.
→ Internal change.
> Enable Stale Bot

- .github/dependabot.yml
This change aims to update the workflow actions automatically by Dependabot.
See also:
- https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/
- https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
None.
→ Internal change.
> Update GitHub Actions by Dependabot

- sider.yml
It's explained by the title.
None.
→ Not notable.
> Use the latest RuboCop on Sider

- lib/runners/harness.rb
- lib/runners/ruby/gem_installer.rb
- lib/runners/workspace.rb
- test/ruby_test.rb
This change aims to make log header messages consistent and readable.
- Analysis started
- Setting up source code
- Setting up RuboCop
- Generating optimized Gemfile...
- Installing gems...
- Running RuboCop
- Analysis finished
- Analysis started
- Set up source code
- Set up RuboCop
- Run RuboCop
- Analysis finished
None.
→ Not notable.
> Make log headers consistent

- lib/runners/issue.rb
- lib/runners/location.rb
- sig/runners/issue.rbi
- sig/runners/location.rbi
- Make the code simpler.
- Improve the type definitions.
None.
→ Internal change.
> Refactor `Issue` and `Location` classes

- lib/tasks/bump/analyzers.rb
This aims to reduce the manual task.
See https://docs.github.com/en/rest/reference/issues#add-labels-to-an-issue
None.
→ Internal change.
> Add label by `rake bump:analyzers`

- lib/runners/processor/clang_tidy.rb
- test/smokes/clang_tidy/expectations.rb
To make debugging easier.
None.
→ Not notable change.
> [Clang-Tidy] Add log messages

- CHANGELOG.md
- lib/runners/results.rb
- lib/runners/schema/result.rb
- sig/runners.rbi
- sig/runners/schema.rbi
- test/result_test.rb
It's self-explanatory.
Fix #1121
→ ~~Internal change.~~
→ This removed class is unused but the interface change. So, I re-think it should be included in the changelog.
> Remove unused `Result::MissingFilesFailure`

- test/harness_test.rb
This is a preparation for #1316.
See also https://github.com/sider/runners_test
Related to #1316
> Refactor `HarnessTest` using `Workspace::Git`

- test/cli_test.rb
- test/harness_test.rb
- test/test_helper.rb
- test/workspace/git_test.rb
- test/workspace_test.rb
This is a preparation for #1316.
> Link related issues or pull requests, e.g. `Fix #123`, `Related to #456`, or `None.`
Related to #1316
> Refactor unit tests using Git workspace

- lib/runners.rb
- lib/runners/workspace.rb
- lib/runners/workspace/git.rb
- sig/polyfill.rbi
- sig/runners/workspace.rbi
- test/workspace/git_test.rb
This change removes the unused methods and logic.
Related to #1316
> Refactor workspace

- images/Dockerfile.java.erb
- images/checkstyle/Dockerfile
- images/detekt/Dockerfile
- images/ktlint/Dockerfile
- images/pmd_cpd/Dockerfile
- images/pmd_java/Dockerfile
The installation moved to sider/devon_rex.
See #1352
See sider/devon_rex#248
> Remove needless Gradle installation

- CHANGELOG.md
- lib/runners/cli.rb
- lib/runners/schema/result.rb
- lib/runners/testing/smoke.rb
- sig/runners/schema.rbi
- sig/runners/testing.rbi
- test/smokes/eslint/expectations.rb
It will be useful for us to look into the analysis results. E.g.
```json
{
"config_file": "sider.yml"
}
```
None.
> Add `config_file` to result

- CHANGELOG.md
- images/stylelint/package.json
- test/smokes/stylelint/only_stylelintrc/.stylelintrc.yaml
This package is active and popular. See <https://github.com/prettier/stylelint-config-prettier>
None.
> [stylelint] Add `stylelint-config-prettier` as pre-installed package

- lib/runners/ignoring.rb
It is self-explanatory from the PR title.
None.
> Small refactoring of `Runners::Ignoring` class

- lib/runners/schema/config.rb
It's self-explanatory from the PR title.
None.
> Small refactoring for `Runners::Schema::Config`

- lib/runners/processor.rb
- test/processor_test.rb
This refactoring is for a better type-checking.
Extracted from #1215
> Refactor `Runners::Processor` class

- lib/runners/workspace.rb
- sig/polyfill.rbi
- test/workspace_test.rb
This refactoring is for a better type-checking.
Extracted from #1215
> Refactor `Runners::Workspace` class

- lib/runners/options.rb
- lib/runners/sensitive_filter.rb
- lib/runners/workspace.rb
- lib/runners/workspace/git.rb
- sig/runners/options.rbi
- test/options_test.rb
This refactoring is for a better type-check.
See #1215
> Refactor `Runners::Options` class

- lib/runners/processor/checkstyle.rb
- test/smokes/checkstyle/config/sideci.yml
- test/smokes/checkstyle/config/src/Foo.java
This refactoring is for a better type-checking.
Related to #1215
> Refactor `Runners::Processor::Checkstyle` class

- lib/runners/processor/cppcheck.rb
This change aims to make the code simpler and clearer.
> Refactor `Runners::Processor::Cppcheck` class

- lib/runners/processor/coffeelint.rb
This change simplifies the class code.
> Refactor `Runners::Processor::Coffeelint` class

- lib/runners/processor/cpplint.rb
This change simplifies the class code.
> Refactor `Runners::Processor::Cpplint` class

- lib/runners/processor/detekt.rb
This change simplifies the class code.
> Refactor `Runners::Processor::Detekt` class

- lib/runners/processor/code_sniffer.rb
This change simplifies the class code.
> Refactor `Runners::Processor::CodeSniffer` class

- querly.yml
This change aims to improve our code review workflow a bit.
- More clear message.
- Add a new justification.
None.
> Improve Querly rule: `sider.runners.exitstatus`

- .github/workflows/build.yml
It's self-explanatory from the title.
Caused by PR #1473
> Fix incorrect `contains()` argument in Actions

- .github/PULL_REQUEST_TEMPLATE.md
This change aims to make the issue template more helpful for pull request's authors.
None.
> Simplify questions and add helpful comments in issue template

- CHANGELOG.md
- bin/runners
- images/docker-entrypoint.sh
- lib/runners/cli.rb
- lib/runners/options.rb
- sig/runners.rbi
- sig/runners/options.rbi
- sig/runners/schema/options.rbi
- sig_new/optparse.rbs
- sig_new/runners/cli.rbs
- sig_new/runners/options.rbs
- test/cli_test.rb
- test/harness_test.rb
- test/options_test.rb
- test/sensitive_filter_test.rb
- test/test_helper.rb
- test/workspace_test.rb
For security, this change aims to delete the environment variables after used.
None.
> Delete environment variables after used

- goodcheck.yml
To prevent bugs like PR #1558.
Related to #1558
> Add Goodcheck rule about `^x.y.z` in package.json

- Gemfile.lock
https://github.com/soutaro/strong_json/compare/v2.1.0...v2.1.2
None.
> Bump strong_json from 2.1.0 to 2.1.2

- .github/workflows/steep.yml
- lib/runners/cli.rb
- lib/runners/harness.rb
- lib/runners/shell.rb
- sig/runners/cli.rbs
- sig/runners/harness.rbs
- sig/runners/ignoring.rbs
- sig/runners/sensitive_filter.rbs
- sig/runners/shell.rbs
- sig/runners/trace_writer.rbs
Copying some `Runners::*` RBS from PR #1215.
A part of #877
> Update RBS for `Runners::*`

- CHANGELOG.md
- images/Dockerfile.python.erb
- images/cpplint/Dockerfile
- images/flake8/Dockerfile
- images/pylint/Dockerfile
- lib/runners/processor/flake8.rb
- lib/runners/python.rb
- test/smokes/flake8/expectations.rb
devon_rex has no longer installed `pyenv`.
See <https://github.com/sider/devon_rex/pull/307>
Closes #603
> Drop Python 2 support

- CHANGELOG.md
- images/cpplint/sider_recommended_CPPLINT.cfg
- lib/runners/processor/cpplint.rb
- test/smokes/cpplint/default_rules/src/foo/sample.cpp
- test/smokes/cpplint/default_rules/src/foo/sample.h
- test/smokes/cpplint/expectations.rb
Fix #1584
If you are adding a new runner:
- ~~[x] Read and follow the [document](https://github.com/sider/runners/blob/master/docs/how-to-write-a-new-runner.md) for a new runner.~~
- ~~[x] Add a new tool to [`analyzers.yml`](https://github.com/sider/runners/blob/master/analyzers.yml).~~
- ~~[x] Run `bundle exec rake readme:generate` and commit the updated `README.md`.~~
- ~~[x] Add a new tool to the [Dependabot configuration](https://github.com/sider/runners/blob/master/.github/dependabot.yml) if needed.~~
- ~~[x] Provide option(s) that users can customize.~~
- ~~[x] Add a [CI setting](https://github.com/sider/runners/blob/master/.github/workflows/build.yml).~~
- ~~[x] Write a [document](https://github.com/sider/sider-docs) and link the pull request, e.g. …
> [cpplint] Enable new recommended configuration

- CHANGELOG.md
- images/docker-entrypoint.sh
- lib/runners/shell.rb
- test/processor_test.rb
Implement a runner timeout message
Close #1552 
Note: this PR don't add new runner.
> Implement analysis timeout message

- lib/runners/processor/cppcheck.rb
- lib/runners/processor/scss_lint.rb
- lib/runners/processor/tslint.rb
This is just a refactoring. No behavior changes.
None.
> Fix warning "assigned but unused variable - stderr"

- .gitmodules
- Steepfile
- lib/runners/trace_writer.rb
- sig/retryable.rbs
- sig/runners/trace_writer.rbs
This adds the Git submodule: https://github.com/soutaro/gem_rbs
By this addition, Retryable's polyfill is needless.
A part of #877
> Fix RBS partially and add soutaro/gem_rbs

- .github/workflows/build.yml
- .github/workflows/test.yml
The change aims to fix the error:
> Error: Unable to process command ...
https://github.com/sider/runners/pull/1656/checks?check_run_id=1422193114#step:2:684
None.
> Fix `check_skip` on Actions [skip ci]

- CHANGELOG.md
- lib/runners/options.rb
- lib/runners/schema/options.rb
- sig/runners/options.rbs
- test/options_test.rb
Reverts sider/runners#1674
This option is no longer required.
> Revert "Add the new option `new_issue_schema`"

- lib/runners/processor.rb
- test/processor_test.rb
For consistency, this change wraps a version number with backquotes.
None.
> Fix message in `Processor#add_warning_if_deprecated_version`

- lib/runners/processor.rb
- sig/runners/processor.rbs
- sig/runners/results.rbs
> Improve RBS for `Runners::Processor`

- lib/runners/cplusplus.rb
- sig/runners/cplusplus.rbs
> Fix RBS for `Runners::CPlusPlus`

- lib/runners/java.rb
- sig/runners/go.rbs
- sig/runners/java.rbs
> Fix RBS for `Runners::Go` and `Runners::Java`

- goodcheck.yml
This change aims to provide such an auto-review like <https://github.com/sider/runners/pull/1703/files#r538954472>.
https://github.com/sider/runners/pull/1703/files#r538954472
> Add Goodcheck rule for TypeScript ESLint

- lib/runners/io.rb
- lib/runners/io/aws_s3.rb
- sig/runners/io.rbs
- sig/runners/io/aws_s3.rbs
This change aims to improve the coverage of type-checking via RBS and Steep.
> Fix RBS for `Runners::IO` classes

- sig/runners/nodejs.rbs
- sig/runners/nodejs/constraint.rbs
- sig/runners/nodejs/dependency.rbs
This change aims to improve the coverage of type-checking via RBS and Steep.
> Fix RBS for `Runners::Nodejs`

- lib/runners/options.rb
- lib/runners/schema/options.rb
- sig/runners/options.rbs
This change aims to improve the RBS and type-check for the `Runners::Options` class.
A part of #877
> Improve RBS for `Runners::Options`

- lib/runners/ruby/gem_installer.rb
- lib/runners/ruby/gem_installer/source.rb
- lib/runners/ruby/gem_installer/spec.rb
- lib/runners/ruby/lockfile_loader/lockfile.rb
- sig/runners/ruby/gem_installer.rbs
- sig/runners/ruby/gem_installer/source.rbs
- sig/runners/ruby/gem_installer/spec.rbs
- sig/runners/ruby/lockfile_loader.rbs
- sig/runners/ruby/lockfile_loader/lockfile.rbs
- sig/runners/ruby/lockfile_parser.rbs
- test/ruby_test.rb
This change aims to improve the RBS and type-check for the modules and classes under `Runners::Ruby::*`.
A part of #877
> Fix RBS for `Runners::Ruby::*` modules/classes

- lib/runners/recommended_config.rb
- sig/runners/recommended_config.rbs
This change aims to improve the RBS and type-check for the `Runners::RecommendedConfig` module.
A part of #877
> Fix RBS for `Runners::RecommendedConfig`

- lib/runners/schema/config.rb
- lib/runners/schema/options.rb
- lib/runners/schema/result.rb
- lib/runners/schema/trace.rb
- sig/runners/schema/config.rbs
- sig/runners/schema/options.rbs
- sig/runners/schema/result.rbs
- sig/runners/schema/trace.rbs
This change aims to improve the RBS and type-check for the `Runners::Schema::*` classes.
A part of #877
> Fix RBS for `Runners::Schema::*` classes

- lib/runners/processor/goodcheck.rb
- sig/runners/processor/goodcheck.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Goodcheck` class.
A part of #877
> Fix RBS for `Runners::Processor::Goodcheck`

- lib/runners/processor/checkstyle.rb
- sig/runners/processor/checkstyle.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Checkstyle` class.
A part of #877
> Fix RBS for `Runners::Processor::Checkstyle`

- lib/runners/processor/haml_lint.rb
- sig/runners/processor/haml_lint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::HamlLint` class.
A part of #877
> Fix RBS for `Runners::Processor::HamlLint`

- lib/runners/processor/querly.rb
- sig/runners/processor/querly.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Querly` class.
A part of #877
> Fix RBS for `Runners::Processor::Querly`

- lib/runners/processor/rails_best_practices.rb
- sig/runners/processor/rails_best_practices.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::RailsBestPractices` class.
A part of #877
> Fix RBS for `Runners::Processor::RailsBestPractices`

- lib/runners/processor/haml_lint.rb
- sig/runners/processor/haml_lint.rbs
- Inline `#run_analyzer` method.
- More strict RBS.
None.
> Refactor `Runners::Processor::HamlLint`

- lib/runners/processor/reek.rb
- sig/runners/processor/reek.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Reek` class.
A part of #877
> Fix RBS for `Runners::Processor::Reek`

- lib/runners/processor/rubocop.rb
- sig/runners/processor.rbs
- sig/runners/processor/rubocop.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::RuboCop` class.
A part of #877
> Fix RBS for `Runners::Processor::RuboCop`

- sig/runners/kotlin.rbs
This change aims to improve the RBS and type-check for the `Runners::Kotlin` module.
A part of #877
> Fix RBS for `Runners::Kotlin`

- CHANGELOG.md
- lib/runners/workspace.rb
- lib/runners/workspace/git.rb
- sig/runners/workspace.rbs
- sig/runners/workspace/git.rbs
- test/workspace/git_test.rb
This class aims to group other error classes under `Runners::Workspace::Git`.
None.
> Add `Runners::Workspace::Git::Error` class

- lib/runners/processor/code_sniffer.rb
- sig/runners/processor/code_sniffer.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::CodeSniffer` class.
A part of #877
> Fix RBS for `Runners::Processor::CodeSniffer`

- .github/PULL_REQUEST_TEMPLATE.md
- docs/how-to-write-a-new-runner.md
There is not much to add to a new Runner.
None.
> Simplify pull request template

- lib/runners/processor/coffeelint.rb
- sig/runners/nodejs.rbs
- sig/runners/processor/coffeelint.rbs
- sig/runners/schema/config.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Coffeelint` class.
A part of #877
> Fix RBS for `Runners::Processor::Coffeelint`

- lib/runners/processor/cppcheck.rb
- sig/runners/processor/cppcheck.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Cppcheck` class.
A part of #877
> Fix RBS for `Runners::Processor::Cppcheck`

- sig/runners/processor/cpplint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Cpplint` class.
A part of #877
> Fix RBS for `Runners::Processor::Cpplint`

- sig/runners/processor/detekt.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Detekt` class.
A part of #877
> Fix RBS for `Runners::Processor::Detekt`

- lib/runners/processor/flake8.rb
- sig/runners/processor/flake8.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Flake8` class.
A part of #877
> Fix RBS for `Runners::Processor::Flake8`

- lib/runners/processor/fxcop.rb
- sig/runners/processor/fxcop.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::FxCop` class.
A part of #877
> Fix RBS for `Runners::Processor::FxCop`

- lib/runners/processor/golangci_lint.rb
- sig/runners/processor/golangci_lint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::GolangCiLint` class.
A part of #877
> Fix RBS for `Runners::Processor::GolangCiLint`

- lib/runners/processor/hadolint.rb
- sig/runners/processor/hadolint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Hadolint` class.
A part of #877
> Fix RBS for `Runners::Processor::Hadolint`

- lib/runners/processor/javasee.rb
- sig/runners/processor/javasee.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Javasee` class.
A part of #877
> Fix RBS for `Runners::Processor::Javasee`

- lib/runners/processor/ktlint.rb
- sig/runners/processor/ktlint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Ktlint` class.
A part of #877
> Fix RBS for `Runners::Processor::Ktlint`

- lib/runners/processor/languagetool.rb
- sig/runners/processor/languagetool.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::LanguageTool` class.
A part of #877
> Fix RBS for `Runners::Processor::LanguageTool`

- sig/runners/location.rbs
This change aims to improve the RBS and type-check for the `Runners::Location` class.
A part of #877
> Fix RBS for `Runners::Location`

- lib/runners/processor/phinder.rb
- sig/runners/processor/phinder.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Phinder` class.
A part of #877
> Fix RBS for `Runners::Processor::Phinder`

- lib/runners/processor/phpmd.rb
- sig/runners/processor/phpmd.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Phpmd` class.
A part of #877
> Fix RBS for `Runners::Processor::Phpmd`

- lib/runners/processor/pmd_cpd.rb
- sig/rexml.rbs
- sig/runners/processor/pmd_cpd.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::PmdCpd` class.
A part of #877
> Fix RBS for `Runners::Processor::PmdCpd`

- lib/runners/processor/pmd_java.rb
- sig/runners/processor/pmd_java.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::PmdJava` class.
A part of #877
> Fix RBS for `Runners::Processor::PmdJava`

- lib/runners/processor/pylint.rb
- sig/runners/processor/pylint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Pylint` class.
A part of #877
> Fix RBS for `Runners::Processor::Pylint`

- lib/runners/processor/remark_lint.rb
- sig/runners/processor/remark_lint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::RemarkLint` class.
A part of #877
> Fix RBS for `Runners::Processor::RemarkLint`

- lib/runners/processor/scss_lint.rb
- sig/runners/processor/scss_lint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::ScssLint` class.
A part of #877
> Fix RBS for `Runners::Processor::ScssLint`

- lib/runners/processor/shellcheck.rb
- sig/runners/processor/shellcheck.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Shellcheck` class.
A part of #877
> Fix RBS for `Runners::Processor::Shellcheck`

- lib/runners/processor/stylelint.rb
- sig/runners/processor/stylelint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Stylelint` class.
A part of #877
> Fix RBS for `Runners::Processor::Stylelint`

- lib/runners/processor/swiftlint.rb
- sig/runners/processor/swiftlint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Swiftlint` class.
A part of #877
> Fix RBS for `Runners::Processor::Swiftlint`

- lib/runners/processor/tslint.rb
- sig/runners/processor/tslint.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Tslint` class.
A part of #877
> Fix RBS for `Runners::Processor::Tslint`

- lib/runners/processor/tyscan.rb
- sig/runners/processor/tyscan.rbs
This change aims to improve the RBS and type-check for the `Runners::Processor::Tyscan` class.
A part of #877
> Fix RBS for `Runners::Processor::Tyscan`

- lib/runners/config.rb
- sig/runners/config.rbs
This change aims to improve the RBS and type-check for the `Runners::Config` class.
A part of #877
> Fix RBS for `Runners::Config`

- lib/runners/testing/smoke.rb
- sig/runners/testing/smoke.rbs
This change aims to improve the RBS and type-check for the `Runners::GitBlameInfo` class.
A part of #877
> Fix RBS for `Runners::Testing::Smoke`

- lib/runners/issue.rb
- lib/runners/processor/clang_tidy.rb
- lib/runners/processor/jshint.rb
- lib/runners/processor/misspell.rb
- lib/runners/processor/phpmd.rb
- lib/runners/processor/pmd_cpd.rb
- lib/runners/processor/pmd_java.rb
- sig/rexml.rbs
- sig/runners/issue.rbs
- sig/runners/processor/pmd_cpd.rbs
This change aims to improve the RBS and type-check for the `Runners::Issue` class.
A part of #877
> Fix RBS for `Runners::Issue`

- lib/runners/analyzer.rb
- sig/runners/analyzers.rbs
This change aims to improve the RBS and type-check for the `Runners::Analyzers` class.
A part of #877
> Fix RBS for `Runners::Analyzers`

- lib/runners/nodejs.rb
- lib/runners/shell.rb
- lib/runners/workspace/git.rb
- sig/rainbow.rbs
- sig/runners/cli.rbs
- sig/runners/harness.rbs
- sig/runners/processor.rbs
- sig/runners/shell.rbs
- sig/runners/testing/smoke.rbs
- sig/runners/trace_writer.rbs
- sig/runners/workspace/git.rbs
This change aims to improve the type-check via RBS and Steep. This also updates `vendor/rbs/gem_rbs/gems/`.
A part of #877
> Improve RBS typecheck

- .github/workflows/steep.yml
`steep check` now is all green! 🎉 
Close #877
> Make Steep check working on Actions

- Gemfile.lock
https://bundler.io/blog/2020/12/09/bundler-v2-2.html
None.
> Bump bundler from 2.1.4 to 2.2.1

- lib/runners/cli.rb
- sig/module.rbs
- sig/optparse.rbs
- sig/runners/cli.rbs
- test/cli_test.rb
- Make some methods private.
- Make the `#processor_class` method more readable.
- Check an argument of `--analyzer` from the available processor classes.
None.
> Refactor `Runners::CLI` class

- lib/runners.rb
https://rubygems.org/gems/shellwords
None.
> Remove unused `shellwords`

- lib/runners/processor/clang_tidy.rb
This change aims to fix the Sider issue:
https://sider.review/gh/repos/202486306/branches/master/commits/105f58e7f9e141147b5b4313112f6d6602a8fd71#issue-107305967
None.
> [Clang-Tidy] Fix performance issue `Performance/CollectionLiteralInLoop`

- tasks/bump/analyzers.rake
This change fixes the following issue:
https://sider.review/gh/repos/202486306/branches/master/commits/9479b92103fd95f0bd7d6fab0d8bc9c956a93585#issue-107317675
None.
> Fix `Lint/ConstantDefinitionInBlock` in `tasks/bump/analyzers.rake`

- Rakefile
```console
$ bundle exec rake --prereqs
rake bump:analyzers
rake bump:devon_rex
rake bump:ruby
rake default
steep:check
test
rake docker:build
dockerfile:generate
rake docker:push
rake docker:shell
rake docker:smoke
rake docker:timeout_test
rake dockerfile:generate
rake dockerfile:verify
rake dockerfile:verify_devon_rex
rake rbs:update_gems
rake readme:generate
rake release
dockerfile:verify_devon_rex
rake steep:check
rake steep:stats
rake test
```
None.
> Simplify rake task dependencies

- lib/runners.rb
`fileutils` is a standard library.
Follow-up of #1856
> Move `require "fileutils"`

- Rakefile
- runners.gemspec
We need to ensure using the same version of Ruby.
Follow-up of #1858
> Make `spec.required_ruby_version` same as `.ruby-version`

- lib/runners/nodejs.rb
This change aims to investigate the cause of #1865. We should revert this change before release.
Related to #1865 
> Add debug code to investigate #1865

- lib/runners/nodejs.rb
This change adds more debug information to look into #1866. I'll revert this later.
Related to #1865 and #1866
> More info for #1865

- lib/runners/nodejs.rb
Fix "where not found".
See #1867
> Remove `where` command

- lib/runners/workspace/git.rb
- sig/runners/workspace/git.rbs
Add more debug log.
To look into #1865 
> More debug log for #1865

- lib/runners/workspace/git.rb
Add more debug log.
To look into #1865.
> Add more debug log for #1865

- lib/runners/workspace/git.rb
Adds more debug log about git-checkout(1) or githooks(5).
Investigation for #1865
> More log about git-checkout

- lib/runners/workspace/git.rb
This adds more log about `.yarnrc`.
Investigation for #1865 
> More log about .yarnrc

- lib/runners/workspace/git.rb
This adds more debug bug about Yarn.
Investigation for #1865
> More log about yarn

- lib/runners/nodejs.rb
- lib/runners/workspace/git.rb
- sig/runners/workspace/git.rbs
The error cause is found, so this reverts the debug code.
See 12ff2ce8...82fb2314
See #1865 
> Revert debug code for #1865

- lib/runners/processor/flake8.rb
- test/smokes/flake8/expectations.rb
This PR remove several debugging code in commits as below
- b49817f962e10598040f58068c16c7f4ad4a81b5
- b2184f363e93cfd989fdc678ee05afc0a61026b9
- 11c107f21bef572c8e0e85985bd1b09158e996c5
Here is a diff URL to check code removing.
https://github.com/sider/runners/compare/a182f02bb972f64757f533f8adbcd245f53436c9...gnakagaw:remove-debug-code-20200104
Note that a182f02bb972f64757f533f8adbcd245f53436c9 is a latest commit by ybiquitous.
> Remove debugging code

- CHANGELOG.md
- lib/runners/processor/flake8.rb
- lib/runners/python.rb
- sig/runners/python.rbs
- Add method: `Runners::Python#pip_install`.
- Run `pip list` to show installed packages for our debug.
- Set `--disable-pip-version-check` to the `pip` command to reduce noises.
(see also <https://github.com/sider/devon_rex/issues/359>)
None.
> Improve `pip install`

- CHANGELOG.md
- lib/runners/python.rb
- Remove packages from the arguments.
- Add `--verbose` option.
```console
$ pip list
Package          Version
---------------- ----------
appdirs          1.4.4
certifi          2020.12.5
distlib          0.3.1
filelock         3.0.12
flake8           3.8.4
mccabe           0.6.1
pip              20.3.3
pipenv           2020.11.15
pycodestyle      2.6.0
pyflakes         2.2.0
setuptools       51.0.0
six              1.15.0
virtualenv       20.2.2
virtualenv-clone 0.5.4
wheel            0.36.2
$ pip list --verbose
Package          Version    Location                                                 Installer
---------------- ---------- -------------------------------------------------------- ---------
appdirs          1.4.4 …
```
> Fix `pip list`

- lib/runners/shell.rb
- sig/runners/shell.rbs
- test/shell_test.rb
This change increases the data that is sent to Bugsnag.
See also <https://ruby-doc.org/core-2.7.2/Process/Status.html>.
None.
> More data on `Shell::ExecError`

- lib/runners/processor/flake8.rb
This PR revert several debug code in #1899 ,#1903 and #1908.
> [Flake8] remove debug code (#1899, #1903, #1908)

- test/smokes/querly/expectations.rb
This is just a change in the code appearance.
None.
> [Querly] Refactor smoke test a bit

- goodcheck.yml
This PR changes `goodcheck.yml` to reduce noises on running `goodcheck check`.
None.
> Exclude some files from Goodcheck

- bin/runners_smoke
- test/smoke.rb
In order to analyze `smoke.rb` on Sider:
https://github.com/sider/runners/blob/389f9227d8df0956d8fb5c4916b293410f03115c/sider.yml#L11-L12
None.
> Move test/smokes/smoke.rb -> test/smoke.rb

- .github/PULL_REQUEST_TEMPLATE.md
It’s self-explanatory from the PR title.
None.
> Clarify "check" description in PR template

- lib/runners/config.rb
- sig/runners/config.rbs
For clients of the `runners` gem.
None.
> Add `Config#validate` alias

- CHANGELOG.md
- lib/runners/config.rb
- sig/runners/config.rbs
- test/config_test.rb
- test/harness_test.rb
This changed method will be used by the gem client.
> Make the `Config#parse` method public

- .github/workflows/build.yml
I'd like to try stopping the retry for the SwiftLint smoke test.
(If the test will be unstable again, let's revert this PR)
See #1217
> [SwiftLint] Remove hack for smoke test on CI

- CHANGELOG.md
- README.md
- analyzers.yml
- lib/runners/analyzers.rb
- sig/runners/analyzers.rbs
- tasks/readme/generate.rake
- test/analyzers_test.rb
Adding a website URL should be useful, not only GitHub URL.
This addition will be used by the `runners` gem users.
None.
> Add `website` to analyzers

- Gemfile.lock
- runners.gemspec
Set it to the same version as devon_rex.
See #1975
> Bump bundler minimum version to 2.2.7

- lib/runners/analyzers.rb
- sig/runners/analyzers.rbs
This stops the lazy initialization of the YAML content for clarity.
Follow up of #1988
> Refactor `Runners::Analyzers#content`

- lib/runners/analyzers.rb
- sig/runners/analyzers.rbs
- test/analyzers_test.rb
This new method should be useful for the gem users.
None.
> Add `Runners::Analyzers#include?` method

- lib/runners.rb
This is just a refactoring for code readability.
None.
> Sort required modules in runners.rb

- test/smokes/eslint/expectations.rb
I cannot find the failure cause, but I think some sub dependencies may be changed.
This should not be related to the Runners' behavior.
None.
> [ESLint] Fix smoke test about "Parsing error"

- lib/runners/processor/haml_lint.rb
- lib/runners/processor/rubocop.rb
- lib/runners/rubocop_utils.rb
- sig/runners/processor/haml_lint.rbs
- sig/runners/processor/rubocop.rbs
- sig/runners/rubocop_utils.rbs
- test/smokes/rubocop/expectations.rb
- test/smokes/rubocop/plugins/.rubocop.yml
- test/smokes/rubocop/plugins/Gemfile
- test/smokes/rubocop/plugins/foo.rb
Added methods: `official_rubocop_plugins`, `third_party_rubocop_plugins`
Follow up of PR #2009
> Add methods to `Runners::RuboCopUtils`

- .gitmodules
- Steepfile
- tasks/rbs/update_gems.rake
See <https://github.com/ruby/gem_rbs_collection#readme>.
Via `git rm vendor/rbs/gem_rbs` command.
None.
> Rename rbs/gem_rbs to rbs/gem_rbs_collection

- CHANGELOG.md
It's a big new feature, so I think it should be stand out.
None.
> Move Slim-Lint to "New features" section in changelog

- README.md
- bin/setup
This change aims to help new-comers set up this project.
Related to #2044
> Add `bin/setup` and simplify README

- lib/runners/processor/golangci_lint.rb
This refactoring aims to improve the code readability a bit.
None.
> [GolangCI-Lint] Refactor `Runners::Processor::GolangCiLint`

- test/smokes/rubocop/expectations.rb
- test/smokes/rubocop/plugins/Gemfile
See <https://github.com/sider/runners/pull/2067/checks?check_run_id=1910632253#step:7:2183>
None.
> [RuboCop] Make feature spec stable

- CHANGELOG.md
- lib/runners/processor/remark_lint.rb
This change aims to make our debugging easier.
Related to #2067
> [remark-lint] Add rule ID to error message

- lib/runners/processor/remark_lint.rb
`master` is not a permalink (unstable).
None.
> Avoid link including `master`

- sig/runners/cli.rbs
- sig/runners/harness.rbs
- sig/runners/processor.rbs
See <https://github.com/ruby/rbs/blob/v1.0.6/docs/syntax.md>
None.
> Improve RBS via `singleton`

- lib/runners/processor/pmd_java.rb
- sig/runners/processor/pmd_java.rbs
- Use `-failOnViolation false` option. (see <https://pmd.github.io/latest/pmd_userdocs_cli_reference.html>)
- Use `-no-cache` to disable warnings about ["Incremental Analysis"](https://pmd.github.io/latest/pmd_userdocs_incremental_analysis.html#disabling-incremental-analysis).
- Inline some methods for simplicity.
None.
> [PMD Java] Refactor `Runners::Processor::PmdJava` class

- lib/runners/processor/hadolint.rb
This change refactors the `Runners::Processor::Hadolint` class via the `--no-fail` flag.
We no longer need to check `status.exitstatus`.
Close #2039
> [hadolint] Refactor via `--no-fail` flag

- CHANGELOG.md
- Gemfile.lock
- lib/runners.rb
- lib/runners/processor/metrics_fileinfo.rb
- runners.gemspec
- sig/parallel.rbs
> [Metrics FileInfo] refactoring processor

- tasks/bump/analyzers.rake
This change aims to fix the bug to unexpectedly commit other analyzers' Dockerfiles.
None.
- [] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.
> Fix `rake bump:analyzers`

- CHANGELOG.md
- lib/runners/processor/checkstyle.rb
- test/smokes/checkstyle/expectations.rb
- test/smokes/checkstyle/google/sider.yml
- test/smokes/checkstyle/google/src/Hello.java
If you are adding a new runner:
- [] ~~Read and follow the [document](https://github.com/sider/runners/blob/master/docs/how-to-write-a-new-runner.md) for a new runner.~~
- [] ~~Add a new tool to [`analyzers.yml`](https://github.com/sider/runners/blob/master/analyzers.yml).~~
- [] ~~Run `bundle exec rake readme:generate` and commit the updated `README.md`.~~
- [] ~~Add a new tool to the [Dependabot configuration](https://github.com/sider/runners/blob/master/.github/dependabot.yml) if needed.~~
- [] ~~Provide option(s) that users can customize.~~
- [] ~~Add a [CI setting](https://github.com/sider/runners/blob/master/.github/workflows/build.yml).~~
- [] Write a [document](https://github.com/sider/sider-docs) and link the pull request -> sider/sider-docs#574
> [Checkstyle] Enable Sider's recommended set of rules

- Gemfile.lock
- https://github.com/amazing-print/amazing_print/releases/tag/v1.3.0
- https://github.com/amazing-print/amazing_print/compare/v1.2.2...v1.3.0
- https://my.diffend.io/gems/amazing_print/1.2.2/1.3.0
None.
> Bump amazing_print from 1.2.2 to 1.3.0

- lib/runners/nodejs.rb
- sig/runners/nodejs.rbs
This refactoring aims to make the code a bit safer via the new constant.
None.
> Add `Runners::Nodejs::PACKAGE_JSON`

- lib/runners/processor/flake8.rb
- sig/runners/processor/flake8.rbs
This is just a refactoring for the `Runners::Processor::Flake8` class.
None.
> [Flake8] Simplify `Runners::Processor::Flake8` a bit

- CHANGELOG.md
- lib/runners/analyzer.rb
- lib/runners/cli.rb
- lib/runners/harness.rb
- sig/runners/cli.rbs
- sig/runners/harness.rbs
- steep_expectations.yml
- test/cli_test.rb
- Make headers consistent.
- More detailed finish messages by result classes (success / failure).
None.
> Improve analysis finish message

- test/nodejs_test.rb
This refactoring avoids testing private methods.
Prepare for #1963
> Refactor NodejsTest

- lib/runners/processor/cppcheck.rb
This is just small refactoring.
Follow-up of #2191
> Small refactoring for #2191

- CHANGELOG.md
- lib/runners/config_generator.rb
> Avoid unintentional string replace (Runners::ConfigGenerator)

- lib/runners/nodejs.rb
- sig/runners/nodejs.rbs
This change is just a fix of typos.
None.
> Fix typo for "satisfied"

- test/nodejs_test.rb
npm 7 supports the installation with [`workspaces`](https://docs.npmjs.com/cli/v7/using-npm/workspaces) like Yarn.
This change adds just a test case to the `Runners::Nodejs` unit test.
None.
> Add test case for `npm install` with `workspaces`

- test/rubocop_utils_test.rb
> Revert skipped test in RubocopUtilsTest

- CHANGELOG.md
- images/pmd_java/sider_recommended_pmd.xml
We provide Sider's recommended ruleset for JAVA PMD.
None.
> [JAVA PMD] Provide Sider's recommended set of rules

- images/shellcheck/Dockerfile
- images/shellcheck/Dockerfile.erb
This change simplifies the ShellCheck runner's Dockerfile via the new devon_rex image.
See also sider/devon_rex#506 and sider/devon_rex#508
> [ShellCheck] Refactor Dockerfile

- images/golangci_lint/Dockerfile
- images/golangci_lint/Dockerfile.erb
- images/hadolint/Dockerfile
- images/hadolint/Dockerfile.erb
- images/javasee/Dockerfile
- images/javasee/Dockerfile.erb
- images/metrics_codeclone/Dockerfile
- images/misspell/Dockerfile
- images/misspell/Dockerfile.erb
- images/pmd_cpd/Dockerfile
- images/pmd_cpd/Dockerfile.erb
- images/pmd_java/Dockerfile
- images/pmd_java/Dockerfile.erb
- images/swiftlint/Dockerfile
- images/swiftlint/Dockerfile.erb
This change is just a simplification of the Dockerfiles.
See sider/devon_rex#508
> Refactor Dockerfiles using `$RUNNER_USER_BIN`

- test/smoke.rb
See the screensthos below:
None.
> Improve smoke test output's appearance

- .github/workflows/build.yml
- tasks/docker/common.rb
- tasks/docker/push.rake
This change aims to clarify and simplify the code about `docker login`.
See also sider/devon_rex#507
> Refactor `docker login` for clarity and simplicity

- test/test_helper.rb
This is extracted from #2317.
See #2317 
> Refactor `with_stubbed_env` test helper method

- lib/runners/nodejs.rb
- sig/runners/nodejs.rbs
- test/nodejs_test.rb
This refactoring aims to simplify the `Nodejs` class.
Extracted from #2317
> Inline `Runners::Nodejs#nodejs_analyzer_local_version` method

- test/rubocop_utils_test.rb
See <https://github.com/sider/runners/actions/runs/788617019>
None.
> Skip unstable Chefstyle assertion

- test/smokes/eslint/expectations.rb
Maybe the cause is a sub-dependency change. Not critical.
See also <https://github.com/sider/runners/runs/2519411066>
None.
> [ESLint] Fix smoke test

- CHANGELOG.md
- Gemfile.lock
- runners.gemspec
It is self-explanatory.
See sider/devon_rex#519
> Bump bundler from 2.2.16 to 2.2.17

- images/pmd_cpd/pmd_cpd
> Revert "[PMD CPD] Add a debug code"

- goodcheck.yml
- sider.yml
This is for our test.
Related to #2418 
> Use the edge version of Goodcheck on Sider

- README.md
- analyzers.yml
It’s self-explanatory.
Follow-up of #2418
> Make secret scanning beta

- CHANGELOG.md
- images/secret_scan/Dockerfile
- images/secret_scan/Dockerfile.erb
- images/secret_scan/Gemfile
- lib/runners/processor/secret_scan.rb
- test/smokes/secret_scan/expectations.rb
It’s a self-explanatory. See also: https://github.com/sider/goodcheck/releases/tag/v3.0.1
Follow-up of #2418
> [Secret Scan] Use the latest version of Goodcheck

- .github/workflows/build.yml
- CHANGELOG.md
See <https://github.com/docker/login-action#aws-public-elastic-container-registry-ecr>
Related to #2464
> Add login to Public ECR

- .github/workflows/build.yml
- CHANGELOG.md
- tasks/docker/common.rb
- tasks/docker/push.rake
- tasks/docker/tag.rake
See https://docs.aws.amazon.com/AmazonECR/latest/public/docker-push-ecr-image.html
Follow-up of #2465
> Publish Docker images to Amazon ECR Public

- .github/workflows/build.yml
This change aims to fix a bug to calculate `steps.define_vars.outputs.publish`.
See #2471
> Fix publish bug from #2471

- .github/workflows/bump_analyzers.yml
This change is just a refactoring for GitHub Action.
None.
> Remove needless `workdflow_dispatch.branches`

- CHANGELOG.md
- Gemfile.lock
- Rakefile
- lib/runners/nodejs.rb
- lib/runners/version.rb
- test/smokes/eslint/expectations.rb
- test/smokes/eslint/private_dependencies/package.json
- test/smokes/eslint/private_dependencies_with_option_dependencies/package.json
- test/smokes/eslint/private_dependencies_with_option_dependencies/sider.yml
This change merges the [`0.50.x`](https://github.com/sider/runners/tree/0.50.x) branch into the `master` branch.
None.
> Merge 0.50.x branch to master

- test/rubocop_utils_test.rb
Some pages return the HTTP 503 error.
None.
> Temporary fix for RuboCopUtilsTest

- .github/workflows/build.yml
It’s self-explanatory. See <https://gallery.ecr.aws/sider/>
Close #2469
> Use custom alias `sider` for Amazon ECR Public

- sider.yml
Using a more accurate `gitignore` pattern.
See <https://help.sider.review/getting-started/custom-configuration#ignore>
Related to #2495
> Fix ignore patterns on sider.yml

- CHANGELOG.md
- lib/runners/processor/querly.rb
The smoke test can fail due to the warnings' order:
https://github.com/sider/runners/runs/2995691401?check_suite_focus=true#step:7:1106
Follow-up of #2516
> [Querly] Sort warnings

- CHANGELOG.md
- lib/runners/processor/querly.rb
- test/smokes/querly/expectations.rb
It's self-explanatory.
Follow-up of #2520
> [Querly] Include file path to warning message

- goodcheck.yml
https://github.com/sider/goodcheck-rules/releases/tag/v0.0.2
None.
> Bump sider/goodcheck-rules from v0.0.1 to v0.0.2

- CHANGELOG.md
- images/phpmd/Dockerfile
- images/phpmd/Dockerfile.erb
- lib/runners/processor/phpmd.rb
- test/smokes/phpmd/expectations.rb
- test/smokes/phpmd/success/app.php
Enable the recommended rulset of PHPMD.
https://github.com/sider/sideci/issues/10670
> [PHPMD] Enable Sider's recommended set of rules

- CHANGELOG.md
- runners.gemspec
To prevent Dependabot errors.
See #2537
> More relax `required_ruby_version`

- goodcheck.yml
https://github.com/sider/goodcheck-rules/releases/tag/v0.0.3
None.
> Bump goodcheck-rules from 0.0.2 to 0.0.3

- CHANGELOG.md
- README.md
- analyzers.yml
The `Secret Scan` is ready to launch. So, I remove the `Beta` flag to release.
https://github.com/sider/sideci/issues/11384
> Move Secret Scan from Beta

- CHANGELOG.md
Fix the wrong changelog that is merged(https://github.com/sider/runners/pull/2529#discussion_r677025827)
- https://github.com/sider/runners/pull/2529
> Fix wrong Changelog of Secret Scan

- test/smokes/detekt/expectations.rb
- test/smokes/detekt/with_options/default-detekt-config.yml
- Rollback the test code that was removed on https://github.com/sider/runners/pull/2616
- Update the `default-detekt-config.yml` file from https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml for testing
- Related: https://github.com/sider/runners/pull/2616
> Rollback test code and change default detekt configuration

- .github/workflows/sider_scan.yml
add a sider scan for GitHub action.
https://github.com/sider/runners/issues/2812
No change logs.
> Introduce Sider Scan runner

- .github/dependabot.yml
> Revert "Disable auto rebasing by dependabot temporarily"

- .github/workflows/sider_scan.yml
I updated the version of Sider Scan to 2.1.0.
https://github.com/sider/runners/issues/2812
> Run sider scan 2.1.0
